# Generated by Django 2.0.9 on 2018-10-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='question',
            field=models.TextField(),
        ),
    ]
