# Generated by Django 2.0.9 on 2018-10-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_reading_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
