# Generated by Django 2.0.9 on 2018-10-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_reading_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
